version: '3.8'

services:
  scraper:
    build: .
    container_name: komepa-scraper
    env_file:
      - .env
    volumes:
      - ./logs:/app/logs
    restart: unless-stopped
    # 定期実行のためのcron設定（1時間ごと）
    command: sh -c "while true; do python scraper.py; sleep 3600; done"